name: 'Lesson Reminder'

on:
  # schedule:
  #   - cron: '00 0 * * *'  #  8:00
  #   - cron: '00 2 * * *'  # 10:00
  #   - cron: '00 6 * * *'  # 14:00
  #   - cron: '00 8 * * *'  # 16:00
  #   - cron: '30 10 * * *' # 18:00
  push:
      branches:
        - main

jobs:
  Reminder:

    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: |
          npm install

      - name: Run
        run: npm run cr -- --mailName=$MAIL_NAME --mailPasswd=$MAIL_PASSWD --databaseId=$DATABASE_ID --notionToken=$NOTION_TOKEN
        env:
          MAIL_NAME: ${{ secrets.MAIL_NAME }}
          MAIL_PASSWD: ${{ secrets.MAIL_PASSWD }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}